version: '3'
networks:
  pysystemtrade-nw:
    driver: bridge
    ipam:
      config:
        - subnet: 10.95.0.0/16
services:
  dashboard:
    container_name: dashboard
    build:
      context: ./
      dockerfile: private/dashboard.Dockerfile
    networks:
      pysystemtrade-nw:
        ipv4_address: 10.95.0.2
    ports:
      - 5001:5000
    restart: unless-stopped
    volumes:
      - ./private:/private:ro
  mongodb:
    container_name: mongodb
    image: mongo:3.6
    networks:
      pysystemtrade-nw:
        ipv4_address: 10.95.0.3
    ports:
      - 27017:27017
    restart: unless-stopped
    volumes:
      - pysystemtrade-mongo-data:/data/db
      - pysystemtrade-mongo-config:/data/configdb
volumes:
  pysystemtrade-mongo-data:
    external: true
    name: pysystemtrade-mongo-data
  pysystemtrade-mongo-config:
    external: true
    name: pysystemtrade-mongo-config
